INCLUDE = .

all: usoabb usoabb2 usoabb3

usoabb : usoabb.cpp ABB.h
	g++ -g -o usoabb -I$(INCLUDE) usoabb.cpp 

usoabb2 : usoabb2.cpp ABB.h 
	g++ -g  -o usoabb2 -I$(INCLUDE) usoabb2.cpp 

usoabb3 : usoabb3.cpp ABB.h
	g++ -g -o usoabb3 -I$(INCLUDE) usoabb3.cpp 
